steps:
#  - step: journal
#    type: file
#    source: $JJFSE
#    target: $JJFSE
#    config:
#      prepare:
#      - name: select
#        columns:
#          - 2
#          - 9
#          - 16
#          - 21
#      - name: map
#        from: 4
#        action: replace
#        enum:
#          - from: 0
#            to: -1
#          - from: 1
#            to: 1
#      - name: expression
#        to: 3
#        expression: "@3 * @4"
#      - name: shuffle
#        by:
#          - 2
  - step: reduce
    type: file
    source:
    target:
    config:
      prepare:
      - name: groupBySum
        groupBy:
          - 2
        sum:
          - 3
      - name: select
        columns:
          - 1
          - 2
          - 3

#  - step: cbf
#    type: file
#    source: $KHYE
#    target: $KHYE
#    config:
#      prepare:
#      - name: select
#        columns:
#          - 2
#          - 9
#          - 16
#
#  - step: lbf
#    type: file
#    source: $KHYE
#    target: $KHYE
#    config:
#      prepare:
#      - name: select
#        columns:
#          - 2
#          - 9
#          - 16
#
#  - step: join
#    type: join
#    target: $BALANCE
#    config:
#      source:
#        - lbf:
#            - 3
#            - 1
#            - 2
#        - journal:
#            - 3
#            - 1
#            - 2
#        - cbf:
#            - 3
#            - 1
#            - 2
#
#  - step: verify
#    source: path/to/input.csv
#    target: path/to/output.csv
#    config:
#      rule:
#        - op: eq
#        - left: "#{@5}"
#        - right: "#{@3+@4}"
#      key:
#        - 1
#        - 2
